### ISSUE TITLE
Unable to continue "The Whispering Door" quest

### ISSUE THREAD

**Issue by lzhfromustc** [alandtse/DialogueMovementEnabler-SE#1]
When this mod is installed, the player can't start dialogue with Mephala during "The Whispering Door". Activate with the door will only make the screen black for a second and set player's position to the door, but no dialogue will show up. If uninstall this mod, player can start the dialogue normally.

**Comment by alandtse** [comment]
Thanks. It's happening for random daedra. 

* Auguer of Dunlain
* Molag Bal

**Comment by alandtse** [comment]
Looks like same bug. https://www.nexusmods.com/skyrimspecialedition/mods/43708?tab=bugs (Hermaeus Mora no dialogue in quest)

**Comment by lzhfromustc** [comment]
Thanks for the reply! Actually this is not a big issue, since save and restart the game will enable that dialogue. Tried when Whisppering Door and Mora didn't talk, and solved the problem.

**Comment by alandtse** [comment]
Actually it's good to hear about the workaround but we should keep this open so if it gets fixed upstream we can remember to fix it.

**Comment by alandtse** [comment]
Fixed in 2.2.0
